server:
  port: 9000
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazing_quizz
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
